apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
spec:
  ignoreCrossplaneConstraints: false
  package: 'crossplane/provider-gcp:master'
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
---  
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-gcp
spec:
  projectID: ${project_id}
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-systems
      name: gcp-provider-creds
      key: osServiceAccount.json