apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rh-sso-operator
  namespace: rh-sso
spec:
  targetNamespaces:
  - rh-sso
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  namespace: rh-sso
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
