kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgresql-{{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"     
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresql-{{ include "spicedb.fullname" . }}
  template:
    metadata:
      labels:
        name: postgresql-{{ include "spicedb.fullname" . }}
    spec:
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-{{ include "spicedb.fullname" . }}
        - name: certs
          secret:
            secretName: postgresql-{{ include "spicedb.fullname" . }}-tls
            defaultMode: 0640
        - name: conf
          configMap:
            name: postgresql-{{ include "spicedb.fullname" . }}                        
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: postgresql
          command:
            - run-postgresql
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-{{ include "spicedb.fullname" . }}
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-{{ include "spicedb.fullname" . }}
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgresql-{{ include "spicedb.fullname" . }}
                  key: database-name
          securityContext:
            capabilities: {}
            privileged: false
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
            - name: certs
              mountPath: /certs
            - name: conf
              mountPath: /opt/app-root/src/postgresql-cfg                      
          terminationMessagePolicy: File
          image: 'registry.redhat.io/rhel8/postgresql-13:latest'
          args:
            - '-c'
            - wal_level=logical
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600