kind: Service
apiVersion: v1
metadata:
  name: postgresql-{{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"    
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: postgresql-{{ include "spicedb.fullname" . }}