apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-{{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"     
data: 
  ssl.conf: |-
    ssl = on
    ssl_cert_file = '/certs/tls.crt' 
    ssl_key_file =  '/certs/tls.key'