kind: Secret
apiVersion: v1
metadata:
  name: postgresql-{{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"    
stringData:
  database-name: spicedb
  database-password: spicedb
  database-user: spicedb
type: Opaque