kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"     
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - endpoints