apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"     
stringData:
  preshared_key: "averysecretpresharedkey"
  datastore_uri: postgres://spicedb:spicedb@postgresql-{{ include "spicedb.fullname" . }}:5432/spicedb?sslmode=disable