kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"     