kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}  
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "spicedb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spicedb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - resources: {}
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-v'
                - '-addr=localhost:50051'
                - '-tls'
                - '-tls-no-verify'
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          name: {{ include "spicedb.fullname" . }}-spicedb
          command:
            - spicedb
            - serve
            - --grpc-tls-cert-path
            - /certs/tls.crt
            - --grpc-tls-key-path
            - /certs/tls.key
            - --dashboard-tls-cert-path
            - /certs/tls.crt
            - --dashboard-tls-key-path
            - /certs/tls.key
            - --dispatch-cluster-tls-cert-path
            - /dispatcher-certs/tls.crt
            - --dispatch-cluster-tls-key-path
            - /dispatcher-certs/tls.key
            - --dispatch-upstream-ca-path
            - /dispatcher-certs/ca.crt                                                    
          livenessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-v'
                - '-addr=localhost:50051'
                - '-tls'
                - '-tls-no-verify'                
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: SPICEDB_LOG_LEVEL
              value: debug
            - name: SPICEDB_DISPATCH_UPSTREAM_ADDR
              value: 'kubernetes:///{{ include "spicedb.fullname" . }}.{{.Release.Namespace}}:dispatch'
            - name: SPICEDB_GRPC_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "spicedb.fullname" . }}
                  key: preshared_key
            - name: SPICEDB_DATASTORE_CONN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "spicedb.fullname" . }}
                  key: datastore_uri
            - name: SPICEDB_DATASTORE_ENGINE
              value: postgres
            - name: SPICEDB_DISPATCH_CLUSTER_ENABLED
              value: 'true'
          ports:
            - name: dahsboard
              protocol: TCP
              containerPort: 8080          
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: dispatch
              containerPort: 50053
              protocol: TCP
            - name: gateway
              containerPort: 8443
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'ghcr.io/authzed/spicedb:v1.13.0'
          volumeMounts:
          - name: certs
            mountPath: /certs
          - name: dispatcher-certs
            mountPath: /dispatcher-certs                   
          - name: ca
            mountPath: /ca               
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ include "spicedb.fullname" . }}
      serviceAccount: {{ include "spicedb.fullname" . }}
      securityContext: {}
      schedulerName: default-scheduler
      volumes:      
      - name: certs
        secret:
          secretName: {{ include "spicedb.fullname" . }}-tls
      - name: dispatcher-certs
        secret:
          secretName: {{ include "spicedb.fullname" . }}-dispatcher-tls             
      - name: ca
        configMap:
          name: openshift-service-ca.crt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600