apiVersion: batch/v1
kind: Job
metadata:
  name: schema-migrate-{{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2" 
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: {{ include "spicedb.fullname" . }}
      serviceAccount: {{ include "spicedb.fullname" . }}
      restartPolicy: OnFailure
      containers:
        - name: {{ include "spicedb.fullname" . }}-migrate
          command:
            - spicedb
            - migrate
            - head
          env:
            - name: SPICEDB_LOG_LEVEL
              value: debug
            - name: SPICEDB_DATASTORE_CONN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "spicedb.fullname" . }}
                  key: datastore_uri
            - name: SPICEDB_SECRETS
              valueFrom:
                secretKeyRef:
                  name: {{ include "spicedb.fullname" . }}
                  key: migration_secrets
                  optional: true
            - name: SPICEDB_DATASTORE_ENGINE
              value: postgres
            - name: SPICEDB_DISPATCH_CLUSTER_ENABLED
              value: 'true'
          terminationMessagePolicy: FallbackToLogsOnError
          image: 'ghcr.io/authzed/spicedb:v1.11.0'
          volumeMounts:
          - name: ca
            mountPath: /ca          
      volumes:
      - name: ca
        configMap:
          name: openshift-service-ca.crt      
  