apiVersion: batch/v1
kind: Job
metadata:
  name: data-load-{{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: {{ include "spicedb.fullname" . }}
      serviceAccount: {{ include "spicedb.fullname" . }}
      restartPolicy: OnFailure      
      containers:
        - name: {{ include "spicedb.fullname" . }}-migrate
          command:
            - zed 
            - import 
            - /data/all-in-one 
            - --token 
            - averysecretpresharedkey
            - --endpoint 
            - "{{ include "spicedb.fullname" . }}:50051"
            - --no-verify-ca
          env:
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "spicedb.fullname" . }}
                  key: preshared_key
          volumeMounts:
          - name: data
            mountPath: "/data"
            readOnly: true
          - name: ca
            mountPath: /ca                              
          terminationMessagePolicy: FallbackToLogsOnError
          image: 'quay.io/authzed/zed:v0.7.4'
      volumes:
        - name: data
          configMap:
            name: {{ include "spicedb.fullname" . }}
        - name: ca
          configMap:
            name: openshift-service-ca.crt                    
  