apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: loki
  namespace: netobserv
spec:
  requestAutoCert: true
  exposeServices:
    console: true
    minio: true
  users:
    - name: loki-user-0
  imagePullSecret: {}
  credsSecret:
    name: loki-secret
  configuration:
    name: loki-env-configuration
  pools:
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - loki
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - pool-0
              topologyKey: kubernetes.io/hostname
      name: pool-0
      resources: {}
      runtimeClassName: ''
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '68719476736'
          storageClassName: managed-nfs-storage
        status: {}
      volumesPerServer: 4
  image: 'minio/minio:RELEASE.2024-01-18T22-51-28Z'
  features: {}
  mountPath: /export

