kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'spire-server-scc-anyuid'
subjects:
  - kind: ServiceAccount
    name: spire-server
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'spire-agent-scc-anyuid'
subjects:
  - kind: ServiceAccount
    name: spire-agent
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'