# Service definition for the admission webhook
apiVersion: v1
kind: Service
metadata:
  name: spire-oidc
  labels:
    {{- include "spire.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: spire-server
  ports:
    - name: https
      port: 443
      targetPort: spire-oidc-port