apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubi8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubi8
  template:
    metadata:
      labels:
        app: ubi8
    spec:
      containers:
      - name: ubi8
        image: gcr.io/spiffe-io/spire-agent:1.5.4
        command:
          - /bin/sh
          - -c
          - | 
            while true 
            do 
              /opt/spire/bin/spire-agent api fetch -socketPath /spiffe-workload-api/agent.sock
              sleep "5"
            done  
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spiffe-workload-api/agent.sock
        volumeMounts:
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true      
        securityContext:
          seLinuxOptions:
            type: allow-csi-socket_openshift-security-profiles.process
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true            