kind: Service
apiVersion: v1
metadata:
  name: loki
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}  
spec:
  selector:
    {{- include "netobserv.selectorLabels" . | nindent 8 }}
  ports:
    - port: 3100
      protocol: TCP
      name: http
    - port: 9096
      protocol: TCP
      name: scheduler