apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-store
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}  
spec:
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce