apiVersion: flows.netobserv.io/v1alpha1
kind: FlowCollector
metadata:
  name: cluster
spec:
  agent: ipfix
  clusterNetworkOperator:
    namespace: openshift-network-operator
  consolePlugin:
    image: 'quay.io/netobserv/network-observability-console-plugin:v0.1.2'
    imagePullPolicy: IfNotPresent
    logLevel: info
    port: 9001
    portNaming:
      enable: true
      portNames:
        '3100': loki
    register: true
    replicas: 1
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 50Mi
  ebpf:
    cacheActiveTimeout: 5s
    cacheMaxFlows: 1000
    excludeInterfaces:
      - lo
    image: 'quay.io/netobserv/netobserv-ebpf-agent:v0.1.0'
    imagePullPolicy: IfNotPresent
    interfaces: []
    logLevel: info
    sampling: 0
  flowlogsPipeline:
    logLevel: info
    port: 2055
    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 100Mi
    prometheusPort: 9090
    imagePullPolicy: IfNotPresent
    enableKubeProbes: true
    kind: DaemonSet
    image: 'quay.io/netobserv/flowlogs-pipeline:v0.1.1'
    replicas: 1
    healthPort: 8080
  ipfix:
    cacheActiveTimeout: 60s
    cacheMaxFlows: 100
    sampling: 400
  loki:
    timeout: 10s
    maxRetries: 10
    maxBackoff: 300s
    staticLabels:
      app: netobserv-flowcollector
    url: 'http://loki:3100/'
    batchWait: 1s
    minBackoff: 1s
    batchSize: 102400
    timestampLabel: TimeFlowEnd
  namespace: network-observability
