apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-anyuid
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}