apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: sa-token
    valueFrom:
      secretKeyRef:
        name: rollouts-sa-token
        key: token         
  metrics:
  - name: success-rate
    interval: 5m
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      web:
        url: http://prometheus.istio-system.svc.cluster.local:9090/api/v1/query?query={{ args.query }}
        headers:
        - key: Authorization
          value: "Bearer {{ args.sa-token }}"
        jsonPath: "{$.data.result}"