kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-rollouts-prometheus-reader
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: bookinfo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
