{{- $frontendUrl := urlParse .Values.appConfig.app.baseUrl}}
{{- $backendUrl := urlParse .Values.appConfig.backend.baseUrl}}
{{- $lighthouseUrl := urlParse .Values.appConfig.lighthouse.baseUrl}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "backstage.fullname" . }}-ingress
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: {{ include "backstage.fullname" . }}-tls
spec:
  host: {{ $frontendUrl.host }}
  port:
    targetPort: 80
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "frontend.serviceName" . }}
---    
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "backstage.fullname" . }}-ingress-backend
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: {{ include "backstage.fullname" . }}-tls  
spec:
  host: {{ $frontendUrl.host }}
  path: /api
  port:
    targetPort: 7000
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "backend.serviceName" . }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "backstage.fullname" . }}-ingress-lighthouse
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: {{ include "backstage.fullname" . }}-tls  
spec:
  host: {{ $frontendUrl.host }}
  path: /lighthouse-api
  port:
    targetPort: 3003
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "lighthouse.serviceName" . }}    
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rootca
spec:
  secretName: rootca
  issuerRef:
    name: self-signer
  commonName: "ca.self-signer.cert-manager"
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: local-issuer
spec:
  ca:
    secretName: rootca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "backstage.fullname" . }}
spec:
  secretName: {{ include "backstage.fullname" . }}-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - backstage
  commonName: backstage
  isCA: false
  usages:
    - server auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - {{ $frontendUrl.host }}   
  issuerRef:
    name: local-issuer
    kind: Issuer
    group: cert-manager.io  