apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: sarif-attestation
spec:
  images:
  - glob: "quay.io/raffaelespazzoli/**"
  authorities:
  - name: keyless-key
    keyless:
      url: "https://fulcio.apps.${base_domain}"
      identities:
        - issuer: https://spire-oidc-spire-system.apps.${base_domain}
          subject: spiffe://cluster1.demo/ns/test-sigstore/sa/pipeline
    ctlog:
      url: https://rekor.apps.tmp-raffa.${base_domain}
    attestations:
    - name: must-have-vuln-attestation
      predicateType: vuln