apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: topic-clone-policy
spec:
  validationFailureAction: enforce
  rules:
  - name: topic-compliance-policy
    match:
      any:
      - resources:
          apiVersion: kafka.strimzi.io/v1beta2
          kinds: 
          - KafkaTopic
          namespaceSelector:
            matchLabels:
              tenant: "true" 
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: Equals
        value: UPDATE              
    validate:
      message: "when updating a topic, replicas cannot change and partitions can only be increased"
      deny:
        conditions:
          any:
          # replicas must not change
            - key: "{{ request.object.spec.replicas }}"
              operator: NotEquals
              value: "{{ request.oldObject.spec.replicas }}"
          # partition can only increase              
            - key: "{{ request.object.spec.partitions }}"
              operator: LessThan
              value: "{{ request.oldObject.spec.partitions }}"              
  - name: topic-clone-policy
    match:
      any:
      - resources:
          apiVersion: kafka.strimzi.io/v1beta2
          kinds: 
          - KafkaTopic
          namespaceSelector:
            matchLabels:
              tenant: "true"
    generate:
      # Kind of generated resource
      kind: KafkaTopic
      # apiVersion of the generated resource
      apiVersion: kafka.strimzi.io/v1beta2
      # Name of the generated resource
      name: "{{request.object.metadata.name}}"
      # namespace for the generated resource
      namespace: "my-kafka"
      # propagate changes from the upstream resource
      synchronize : true
      clone:
        namespace: "{{request.object.metadata.namespace}}"
        name: "{{request.object.metadata.name}}"