apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "nfd-operator"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  labels:
    operators.coreos.com/nfd.openshift-operators: ""
  name: nfd
spec:
  channel: "4.6"
  installPlanApproval: Automatic
  name: nfd
  source: redhat-operators
  sourceNamespace: openshift-marketplace