kind: Secret
apiVersion: v1
metadata:
  name: spicedb-database-secret
stringData:
  database-name: spicedb
  database-password: spicedb
  database-user: spicedb
type: Opaque
---
kind: Service
apiVersion: v1
metadata:
  name: spicedb-database
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: spicedb-database
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spicedb-database-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spicedb-database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spicedb-database
  template:
    metadata:
      labels:
        name: spicedb-database
    spec:
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: spicedb-database-volume
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: postgresql
          command:
            - run-postgresql
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: spicedb-database-secret
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spicedb-database-secret
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: spicedb-database-secret
                  key: database-name
          securityContext:
            capabilities: {}
            privileged: false
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
          terminationMessagePolicy: File
          image: 'registry.redhat.io/rhel8/postgresql-13:latest'
          args:
            - '-c'
            - wal_level=logical
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600