kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dev
  labels:
    authzed.com/cluster: dev
    authzed.com/cluster-component: spicedb-service
    authzed.com/managed-by: operator
spec:
  to:
    kind: Service
    name: dev
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
---
kind: Service
apiVersion: v1
metadata:
  name: dev
  labels:
    authzed.com/cluster: dev
    authzed.com/cluster-component: spicedb-service
    authzed.com/managed-by: operator
spec:
  ports:
    - name: dahsboard
      protcol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: dispatch
      protocol: TCP
      port: 50053
      targetPort: 50053
    - name: gateway
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
  selector:
    authzed.com/cluster: dev
    authzed.com/cluster-component: spicedb
    authzed.com/managed-by: operator
---    
apiVersion: v1
kind: Secret
metadata:
  name: dev-spicedb-config
stringData:
  preshared_key: "averysecretpresharedkey"
  #datastore_uri: postgres://admin@cockroachdb-public:26257/defaultdb?sslmode=disable
  datastore_uri: postgres://spicedb:spicedb@spicedb-database:5432/spicedb?sslmode=disable
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: dev
  labels:
    authzed.com/cluster: dev
    authzed.com/cluster-component: spicedb-serviceaccount
    authzed.com/managed-by: operator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev
  labels:
    authzed.com/cluster: dev
    authzed.com/cluster-component: spicedb-role
    authzed.com/managed-by: operator
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - endpoints
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev
  labels:
    authzed.com/cluster: dev
    authzed.com/cluster-component: spicedb-rolebinding
    authzed.com/managed-by: operator
subjects:
  - kind: ServiceAccount
    name: dev
    namespace: spicedb-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-spicedb
  labels:
    authzed.com/cluster: dev
    authzed.com/cluster-component: spicedb
    authzed.com/managed-by: operator
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: dev-spicedb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dev-spicedb
        authzed.com/cluster: dev
        authzed.com/cluster-component: spicedb
        authzed.com/managed-by: operator
      annotations:
        authzed.com/spicedb-secret: n699h78hb5hb4h68ch578h7fh6cq
    spec:
      containers:
        - resources: {}
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-v'
                - '-addr=localhost:50051'
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          name: dev-spicedb
          command:
            - spicedb
            - serve
          livenessProbe:
            exec:
              command:
                - grpc_health_probe
                - '-v'
                - '-addr=localhost:50051'
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: SPICEDB_LOG_LEVEL
              value: debug
            - name: SPICEDB_DISPATCH_UPSTREAM_ADDR
              value: 'kubernetes:///dev.spicedb-test:dispatch'
            - name: SPICEDB_GRPC_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-spicedb-config
                  key: preshared_key
            - name: SPICEDB_DATASTORE_CONN_URI
              valueFrom:
                secretKeyRef:
                  name: dev-spicedb-config
                  key: datastore_uri
            - name: SPICEDB_DATASTORE_ENGINE
              value: postgres
            - name: SPICEDB_DISPATCH_CLUSTER_ENABLED
              value: 'true'
          ports:
            - name: dahsboard
              protcol: TCP
              containerPort: 8080          
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: dispatch
              containerPort: 50053
              protocol: TCP
            - name: gateway
              containerPort: 8443
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'ghcr.io/authzed/spicedb:v1.13.0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: dev
      serviceAccount: dev
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
