apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-security-profiles
  namespace: openshift-security-profiles
spec:
  upgradeStrategy: Default
--- 
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: security-profiles-operator
  namespace: openshift-security-profiles
spec:
  channel: release-alpha-rhel-8
  installPlanApproval: Automatic
  name: security-profiles-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

