apiVersion: security-profiles-operator.x-k8s.io/v1alpha2
kind: SelinuxProfile
metadata:
  name: allow-csi-socket
spec:
  allow:
    container_var_run_t:
      sock_file:
        - write
    var_run_t:
      sock_file:
        - write        
  inherit:
    - kind: System
      name: container
  permissive: false