apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: letsencrypt-cert-manager-dns
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action: 
      - 'route53:GetChange'
      effect: Allow
      resource: 'arn:aws:route53:::change/*'
    - action:
      - 'route53:ChangeResourceRecordSets'
      - 'route53:ListResourceRecordSets'
      #- 'route53:GetChange'
      #- 'route53:ListHostedZonesByName'
      #- 'route53:ListHostedZones'
      effect: Allow
      resource: 'arn:aws:route53:::hostedzone/${hosted_zone}'     
    - action:
      - "route53:ListHostedZonesByName"
      effect: "Allow"
      resource: "*"   
  secretRef:
    name: cert-manager-dns-credentials
    namespace: cert-manager