kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "grafana-ocp.labels" . | nindent 4 }}  
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: grafana-serviceaccount
roleRef:
  kind: ClusterRole
  name: grafana
  apiGroup: rbac.authorization.k8s.io