apiVersion: v1
kind: ConfigMap
metadata:
  name: service-ca
  labels:
    {{- include "ess-plugin-vault.labels" . | nindent 4 }}  
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}