apiVersion: v1
kind: Service
metadata:
  name: {{ include "ess-plugin-vault.fullname" . }}
  labels:
    {{- include "ess-plugin-vault.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ess-server-certs  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "ess-plugin-vault.selectorLabels" . | nindent 4 }}
