kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contour-projectcontour-referencepolicies
rules:
  - verbs:
      - get
      - list
      - watch
      - update
    apiGroups:
      - gateway.networking.k8s.io
    resources:
      - referencepolicies
  - verbs:
      - create
      - get
      - update
    apiGroups:
      - gateway.networking.k8s.io
    resources:
      - referencepolicies/status
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contour-projectcontour-referencepolicies
subjects:
  - kind: ServiceAccount
    name: contour
    namespace: projectcontour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour-projectcontour-referencepolicies
